name: 'AWS Deploy S3 File Sample'

on:
  push:
    branches:
      - 'main'

jobs:
  sample:
    name: sample
    runs-on: ubuntu-latest
    steps:
      - name: Create a static folder & file
        run: mkdir sample && echo hello > sample/sample.txt && echo nice > sample/sample2.txt
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_S3_REGION }}
      - name: Deploy static files to AWS S3
        id: aws-deploy-s3
        uses: oneyedev/aws-deploy-s3@main
        with:
          region: ${{ secrets.AWS_S3_REGION }}
          bucket: ${{ secrets.AWS_S3_BUCKET }}
          source: './sample'
          target: 'sample'
